import { Inter } from 'next/font/google';
import './globals.css';
import Header from './(routes)/_components/Header';
import Footer from './(routes)/_components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header activeHome />
				{/* {children}
        <Footer/> */}
			</body>
		</html>
	);
}
