'use client';
import { Inter } from 'next/font/google';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { NextUIProvider } from '@nextui-org/react';
import ThemeProvider from './(routes)/_components/ThemeProvider';
import App from './(routes)/app';
const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
// 	title: 'FT BOOK',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={inter.className}>
					<ThemeProvider>
						<NextUIProvider>
							<App children={children} />
						</NextUIProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
